adminUser:
  password: local:jaguarivy/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: pmuir@bleepbleep.org.uk
  token: local:jaguarivy/pipelineUser:token
  username: muirp-owner
prow:
  hmacToken: local:jaguarivy/prow:hmacToken
